<a href="https://colab.research.google.com/github/Aleybryan17/Alejandra/blob/main/Examen_08_11_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)
pass

NumPy version: 1.23.5


In [ ]:
arr = np.arange(10)

print(arr)
pass

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
vector_aleatorio = np.random.rand(10)

print("Vector aleatorio original:")
print(vector_aleatorio)

indice_maximo = np.argmax(vector_aleatorio)

vector_aleatorio[indice_maximo] = 0

print("Vector aleatorio con el valor máximo reemplazado por 0:")
print(vector_aleatorio)
pass

Vector aleatorio original:
[0.91049419 0.61476308 0.11706474 0.45798901 0.64872209 0.87167276
 0.32587944 0.54192888 0.95101649 0.30607855]
Vector aleatorio con el valor máximo reemplazado por 0:
[0.91049419 0.61476308 0.11706474 0.45798901 0.64872209 0.87167276
 0.32587944 0.54192888 0.         0.30607855]


In [ ]:

matriz = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

numero = matriz[1, 2]

print("El número 8 en la matriz es:", numero)
pass

El número 8 en la matriz es: 8


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

subset = arr[2:5]

print("Los numeros [3, 4, 5] en la matriz son:", subset)
pass

Los numeros [3, 4, 5] en la matriz son: [3 4 5]


In [ ]:
matriz = np.array([1, 2, 3, 4, 5, 6, 7])

numeros = matriz[-4:]

print("Los últimos 4 números en la matriz son:", numeros)
pass

Los últimos 4 números en la matriz son: [4 5 6 7]


In [ ]:
matriz = np.full((3, 3), True, dtype=bool)

print(matriz)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

numeros_impares = arr[arr % 2 != 0]

print("Números impares en la matriz arr:", numeros_impares)
pass

Números impares en la matriz arr: [1 3 5 7 9]


In [ ]:
vector = np.arange(10, 50)

print(vector)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
vector = [1, 2, 3, 4, 5]

vector_invertido = vector[::-1]

print("Vector original:", vector)
print("Vector invertido:", vector_invertido)
pass

Vector original: [1, 2, 3, 4, 5]
Vector invertido: [5, 4, 3, 2, 1]


In [ ]:
matriz = np.random.randint(1, 101, (10, 10))

minimo_valor = np.min(matriz)
maximo_valor = np.max(matriz)

print("Matriz aleatoria de 10x10:")
print(matriz)
print("Valor mínimo en la matriz:", minimo_valor)
print("Valor máximo en la matriz:", maximo_valor)
pass

Matriz aleatoria de 10x10:
[[ 46  40  57  42  89  54  21 100  45  55]
 [  1  22  34  14  48   6  50  45  94   9]
 [ 46  86  39  97  50  58  93  29  21  52]
 [ 51  97   6  75  83  72  48  85  51  10]
 [  2  72  61  13  74  85  71  21  75  48]
 [ 51  98  62  16  64  28  77  74   8  50]
 [ 29  58  79  99  69   5   8   4  64  23]
 [ 56  62   7  42  99  46  55  32  64  46]
 [ 46  41  44   2  23  86  48  37  99  60]
 [ 63  74  40  37   8  18  57  92  73  76]]
Valor mínimo en la matriz: 1
Valor máximo en la matriz: 100


In [ ]:
random_array = np.random.rand(3, 3, 3)

print(random_array)
pass

[[[0.90365329 0.46827901 0.03829225]
  [0.18450993 0.9105149  0.59478493]
  [0.82078259 0.37756179 0.59193711]]

 [[0.79866331 0.47264072 0.94452695]
  [0.43626372 0.47375033 0.41302918]
  [0.12140628 0.77076951 0.24154251]]

 [[0.5604782  0.10899003 0.89544748]
  [0.37482084 0.65840535 0.24188793]
  [0.08199378 0.94855051 0.21343329]]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1

print("Arreglo con números impares reemplazados por -1:", arr)
pass

Arreglo con números impares reemplazados por -1: [-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
import numpy as np

float_array = np.array([1.0, 2.5, 3.7, 4.2, 5.9])

print(float_array)
pass

[1.  2.5 3.7 4.2 5.9]


In [2]:
import numpy as np
matriz_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

matriz_2d = matriz_1d.reshape(2, -1)

print(matriz_2d)
pass

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np

Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)

valores_comunes = np.intersect1d(Z1, Z2)

print("Matriz 1:", Z1)
print("Matriz 2:", Z2)
print("Valores comunes:", valores_comunes)
pass

Matriz 1: [1 8 9 5 9 7 6 0 2 8]
Matriz 2: [4 1 5 3 1 0 3 7 1 0]
Valores comunes: [0 1 5 7]


In [4]:
import numpy as np

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

son_iguales = np.array_equal(A, B)

print("Matriz A:", A)
print("Matriz B:", B)

if son_iguales:
    print("Las matrices son iguales.")
else:
    print("Las matrices no son iguales.")

pass

Matriz A: [1 1 0 0 0]
Matriz B: [0 0 0 0 0]
Las matrices no son iguales.


In [6]:
import numpy as np

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

resultado = np.vstack((A, B))

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatrices apiladas verticalmente:")
print(resultado)
pass

Matriz A:
[0 1 0 1 0]

Matriz B:
[0 0 1 1 0]

Matrices apiladas verticalmente:
[[0 1 0 1 0]
 [0 0 1 1 0]]


In [7]:
import numpy as np

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

resultado = np.hstack((A, B))

print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nMatrices apiladas horizontalmente:")
print(resultado)
pass

Matriz A:
[1 1 1 0 0]

Matriz B:
[1 0 1 1 1]

Matrices apiladas horizontalmente:
[1 1 1 0 0 1 0 1 1 1]


In [9]:
import numpy as np

tmp = np.arange(15)

elementos_entre_5_y_10 = tmp[(tmp >= 5) & (tmp <= 10)]

print("Matriz tmp:")
print(tmp)
print("\nElementos entre 5 y 10:")
print(elementos_entre_5_y_10)

# pass

Matriz tmp:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Elementos entre 5 y 10:
[ 5  6  7  8  9 10]


In [12]:
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


vectorized_maxx = np.vectorize(maxx)


a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

result = vectorized_maxx(a, b)


print(result)



[6 7 9 8 9 7 5]


In [14]:
import numpy as np

arr = np.arange(9).reshape(3, 3)
print("Matriz original:")
print(arr)

arr[:, [1, 2]] = arr[:, [2, 1]]

print("\nMatriz después de intercambiar las columnas 1 y 2:")
print(arr)
pass


Matriz original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Matriz después de intercambiar las columnas 1 y 2:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [16]:
import numpy as np

matriz_aleatoria = np.random.uniform(5, 10, size=(5, 3))

print(matriz_aleatoria)

[[7.72989122 5.69632698 6.15817952]
 [7.6381323  6.26631899 8.1161195 ]
 [7.78176323 5.53886398 9.79597051]
 [7.99433958 7.8579453  5.20604944]
 [7.45022678 9.95749317 7.73605251]]
